-- URBNWAVE Supabase schema
-- Run this in Supabase SQL editor

create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price integer not null,
  image text not null,
  description text not null,
  volume integer not null,
  family text not null check (family in ('цитрус', 'древесный', 'восточный', 'цветочный')),
  is_new boolean default false,
  is_hit boolean default false,
  sale_percent integer,
  popularity integer default 0,
  release_year integer default extract(year from now()),
  longevity text default 'средний' check (longevity in ('легкий', 'средний', 'стойкий')),
  inspired_by text,
  notes jsonb default '{"top":[],"heart":[],"base":[]}'::jsonb,
  scenarios text[] default '{}',
  gallery text[] default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'new' check (status in ('new', 'confirmed', 'packed', 'shipped', 'done', 'cancelled')),
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  customer_city text,
  total integer not null,
  items jsonb not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.site_content (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz default now()
);

insert into public.site_content(key, value)
values
  ('hero', '{"title":"Премиальный бренд распива и авторского парфюма URBNWAVE","subtitle":"Сильная воронка: сначала именитые распивы, затем переход в вашу Atelier-линейку.","badge":"-15% на первый заказ","image":"/images/perfume/photo_11_2026-03-03_11-43-39.jpg"}'::jsonb),
  ('menu', '{"catalog":"Весь каталог","decants":"Именитые распивы","atelier":"Atelier URBNWAVE","top":"Популярные распивы","quiz":"Подбор"}'::jsonb),
  ('benefits', '{"items":[{"title":"Доставка 1-3 дня","text":"Москва, СПб и вся РФ"},{"title":"Контроль качества","text":"Партии и розлив фиксируются"},{"title":"Возврат 14 дней","text":"Прозрачные условия без бюрократии"}]}'::jsonb),
  ('brand', '{"title":"Премиальный бренд, который продает и вызывает доверие","subtitle":"Стратегия URBNWAVE: покупатель сначала тестирует знакомые ароматические направления в распиве, затем знакомится с вашей авторской линией.","image":"/images/perfume/photo_6_2026-03-03_11-43-39.jpg","points":["Именитые ароматы на распив для первого доверия к качеству.","Atelier-линейка URBNWAVE для перехода на ваш собственный бренд.","Премиальный визуал, упаковка и прозрачная клиентская коммуникация."]}'::jsonb),
  ('pages', '{"delivery":{"title":"Доставка","text":"Доставляем по всей России. Курьер, ПВЗ и экспресс-доставка."},"returns":{"title":"Возврат","text":"Вы можете вернуть товар в срок до 14 дней при соблюдении условий."},"payment":{"title":"Оплата","text":"Онлайн-оплата пока не подключена. Заказы подтверждаются менеджером в WhatsApp/Telegram."},"faq":{"title":"Вопросы","text":"Ответы о распиве, доставке и оплате."},"about":{"title":"О бренде","text":"URBNWAVE: именитые ароматы для доверия и Atelier-линейка для роста собственного бренда."},"contacts":{"title":"Контакты","text":"support@urbnwave.ru и Telegram @urbnwave_support"},"stores":{"title":"Магазины","text":"Офлайн-точки и партнерские пространства в Москве и Санкт-Петербурге."},"careers":{"title":"Карьера","text":"Ищем сильных людей в маркетинг, продукт и retail."}}'::jsonb),
  ('faq_items', '{"items":[{"question":"Что такое распив?","answer":"Это возможность протестировать аромат в меньшем объеме перед покупкой полноразмера."},{"question":"Как долго держится аромат?","answer":"Стойкость зависит от композиции и типа кожи, обычно от 4 до 10 часов."}]}'::jsonb)
on conflict (key) do nothing;

-- updated_at trigger helper
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists trg_site_content_updated_at on public.site_content;
create trigger trg_site_content_updated_at
before update on public.site_content
for each row execute function public.set_updated_at();

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.site_content enable row level security;

-- Public read for storefront
drop policy if exists "products_select_public" on public.products;
create policy "products_select_public" on public.products
for select
using (true);

drop policy if exists "site_content_select_public" on public.site_content;
create policy "site_content_select_public" on public.site_content
for select
using (true);

-- Public create for checkout
drop policy if exists "orders_insert_public" on public.orders;
create policy "orders_insert_public" on public.orders
for insert
with check (true);

-- Admin access (authenticated users)
drop policy if exists "products_manage_auth" on public.products;
create policy "products_manage_auth" on public.products
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "site_content_manage_auth" on public.site_content;
create policy "site_content_manage_auth" on public.site_content
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "orders_manage_auth" on public.orders;
create policy "orders_manage_auth" on public.orders
for select
using (auth.role() = 'authenticated');

drop policy if exists "orders_update_auth" on public.orders;
create policy "orders_update_auth" on public.orders
for update
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "orders_delete_auth" on public.orders;
create policy "orders_delete_auth" on public.orders
for delete
using (auth.role() = 'authenticated');

-- Storage bucket for CMS image uploads
insert into storage.buckets (id, name, public)
values ('site-assets', 'site-assets', true)
on conflict (id) do nothing;

drop policy if exists "site_assets_public_read" on storage.objects;
create policy "site_assets_public_read" on storage.objects
for select
using (bucket_id = 'site-assets');

drop policy if exists "site_assets_auth_insert" on storage.objects;
create policy "site_assets_auth_insert" on storage.objects
for insert
with check (bucket_id = 'site-assets' and auth.role() = 'authenticated');

drop policy if exists "site_assets_auth_update" on storage.objects;
create policy "site_assets_auth_update" on storage.objects
for update
using (bucket_id = 'site-assets' and auth.role() = 'authenticated')
with check (bucket_id = 'site-assets' and auth.role() = 'authenticated');

drop policy if exists "site_assets_auth_delete" on storage.objects;
create policy "site_assets_auth_delete" on storage.objects
for delete
using (bucket_id = 'site-assets' and auth.role() = 'authenticated');
